// Div that will contain the app
const appRoot = document.getElementById('app');
const app = {
  title: 'Indecision App',
  subtitle: 'The app for people who can\'t stand making decisions!',
  options: []
};

// Function to generate the options
function displayOptions(options){
  // Only runs if there are items in the options array
  if (options.length > 0){
    return <div><p>Here are your options:</p>
          <ul>
            <li>Item 1</li>
            <li>Item 2</li>
          </ul></div>
  } else {
    return <p>No options</p>
  }
}

const onFormSubmit = (e) => {
  e.preventDefault();
  const option = e.target.elements.option.value;
  
  if(option){
    app.options.push(option);
    e.target.elements.option.value = '';
    renderIndecisionApp();
  }
};

const onRemoveAll = () => {
  app.options = [];
  renderIndecisionApp();  
};


const renderIndecisionApp = () => {

  // JSX - JavaScript XML
  // This is a JavaScript extension included within React
  // Note that app.subtitle is only displayed if it exists - the first part of the statement must be truth
  // The options are generated by a separate function
  const template = (
    <div>
      <h1>{app.title}</h1>
      {app.subtitle && <p>{app.subtitle}</p>}
      <p>{app.options.length}</p>
      <button onClick={onRemoveAll}>Remove All</button>
      {displayOptions(app.options)}
      <form onSubmit={onFormSubmit}>
        <input type="text" name="option" />
        <button>Add Option</button>
      </form>
  </div>
  );

  ReactDOM.render(template, appRoot);
};

renderIndecisionApp();